# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt dist-upgrade -y
    apt install nmap dnsmap net-tools -y
    apt install -y openvpn dialog python3-pip python3-setuptools
    pip3 install protonvpn-cli
    apt install -y recon-ng
  SHELL
end
